In this thesis, we investigate the eddy currents induced in the rail of a homogeneous electromagnetic suspension (EMS) system.
Of particular interest is the induced magnetic field generated by the eddy currents, more precisely its profile in the direction of motion depending on the velocity of the vehicle and the geometry of the rail. The resulting forces are fundamental for the stability and efficiency of the suspension system, especially at high velocities as targeted in the Hyperloop.


After introducing the theoretical basics of electromagnetism, we derive various analytical models to describe the eddy currents and their effects on the magnetic field. We then simulate the eddy currents with the finite element method (FEM) using two simulation software packages (Ansys Maxwell and Ansys Mechanical) for different geometries and velocities and compare the results with each other.

The insights gained contribute to the understanding of eddy current phenomena in homogeneous EMS systems and provide qualitative and quantitative information about the effects on the levitation behavior and the impaired efficiency due to braking effects. Furthermore, possible approaches to reduce the eddy currents are identified to improve the performance of EMS-based transportation systems.
