#pagebreak()
= Eddy Current Models <chapter:eddy_currents_models>

In the following chapter, different models are presented to describe the
eddy currents which are generated by the magnetic field and the movement
of the magnet.

== Yamamura model
<yamamura-model>
In his paper from 1975 @yamamura1975, Yamamura proposed an analytical
model for speed characteristics of attracting magnets for magnetic
levitation. The model here is simplified in the following form that rail
and magnet core are not bent any more but are straight as shown in
figure @fig:yamamura_simplified.

#figure(caption: [Comparison of the magnetic circuit and the simplified magnetic circuit],
  grid(columns: 2,
  column-gutter: 1em,
  row-gutter: 0.5em,
  [#image("../figures/mag_circuit.svg", width: 100%)],
  [#image("../figures/yamamura_simplified.svg", width: 60%)],
  [(a) Schematic of the magnetic circuit],[(b) Schematic of the simplified magnetic circuit]
  )
)<fig:yamamura_simplified>

We use the following three equations:
$ arrow(J) = sigma (arrow(E) + arrow(v) times arrow(B)) $<eq:current_density>

which describes the current density in the conductor generated by an electric field $arrow(E)$ and the Lorentz force, which depends on the magnetic field $arrow(B)$ and the velocity $arrow(v)$. Furthermore, we use two static maxwell equations:
$ nabla times arrow(E) = 0 $<eq:maxwell_E1>
$ nabla times arrow(B) = mu arrow(J) $
By integrating a closed path from rail to magnet in x and z direction, we can derive the following equations:
$ frac(partial b, partial x) = frac(mu_0 d, g) j_z $<eq:path_integraded1>
$ frac(partial b, partial z) = - frac(mu_0 d, g) j_x $<eq:path_integraded2>
where $mu_0$ is the permeability of air. Combining equation @eq:maxwell_E1 and @eq:current_density and applying a cross product on them holds following equation:
$ nabla times arrow(J) = sigma nabla times (nabla times arrow(B)) $<eq:double_cross_product>
Inserting equations @eq:path_integraded1 and @eq:path_integraded2 into
equation @eq:double_cross_product yields:
$ frac(partial^2 b, partial x^2) + frac(partial^2 b, partial z^2) - K frac(partial b, partial x) = 0 $<eq:wave_equation>
where $K = frac(mu_0 sigma d v, g)$. The magnetic flux density can be
split into two parts, the component $b_e$ excited by the coils and the
component $b_i$ induced by the eddy currents in the rail.
$ b = b_e + b_i $ Assumption is made that the excited component $b_e$ is
constant $B_0$ inside the air gap along the magnet and 0 elsewhere.
$ b_e = B_0 (u (x) - u (x - L)) (u (z + a) - u (z - a)) $<eq:solution_b_e>
$u (x)$ and $u (z)$ are step functions. \

Within the air gap $(0 < x < L , - a < z < a)$ the derivation of $b_e$
is there, so equation @eq:wave_equation simplifies to
$ frac(partial^2 b_i, partial x^2) + frac(partial^2 b_i, partial z^2) - K frac(partial b_i, partial x) = 0 $<eq:simplified_wave_equation>
An Ansatz of separated variables is assumed
$ b_i (x , z) = X (x) Z (z) $<eq:separated_variables>
which leads to
$ frac(d^2 Z (z), d z^2) + lambda_n Z (n) = 0 $ where $lambda_n$ is an
arbitrary constant. Boundary conditions are $b_i = 0$ at
$z = plus.minus a$ which gives following solution
$ Z (n) = cos (lambda_n z) $<eq:solution_z>
$ lambda_n = (2 n - 1) frac(pi, 2 a) $
Combining equations @eq:solution_z and @eq:separated_variables yields
$ b_i (x , z) = X (x) cos (lambda_n z) $ \

The step functions in equation @eq:solution_b_e can be expressed by
following Fourier series
$ u (z + a) - u (z - a) = sum_(n = 1)^oo c_n cos lambda_n z $
$ c_n = frac(4, pi (2 n - 1)) sin frac(2 n - 1, 2) pi $ \
Regarding the exciting component of equation @eq:wave_equation and
neglecting $frac(partial^2 b_e, partial z^2)$ (since motion is only in
$x$-direction) holds
$ f (x , z) = & B_0 [- frac(d, d x) (delta (x) - delta (x - L)) \ &+ K (delta (x) - delta (x - L))] x (sum_(n = 1)^oo c_n cos lambda_n z) $
Inserting in equation @eq:simplified_wave_equation and considering
orthogonality of $cos lambda_n z$ yields
$ & frac(d^2 X_n, d x^2) - K frac(d X_n, d x) - lambda_n X_n \ & = C_n B_0 \( - frac(d, d x) (delta (x) - delta (x - L) + K (delta (x) - delta (x - L))) $
This equation can effectively be solved by Fourier transformation. The
solution is
$  & upright("for ") x < 0 : &  & X_n (x) = c_n B_0 frac(alpha_n, alpha_n - beta_n) (exp { - beta_n x } - exp { - beta_n (x - L) })\
 & upright("for ") 0 < x < L : &  & X_n (x) = c_n B_0 frac(1, alpha_n - beta_n) (beta_n exp { - alpha_n x } - alpha_n exp { - beta_n (x - L) })\
 & upright("for ") L < x : &  & X_n (x) = c_n B_0 frac(beta_n, alpha_n - beta_n) (exp { - alpha_n x } - exp { - alpha_n (x - L) }) $
with the following factors:
$ alpha_n & = 1 / 2 (- K + sqrt(K^2 + 4 lambda_n^2)) $
$ beta_n & = 1 / 2 (- K - sqrt(K^2 + 4 lambda_n^2)) $
So the solution for the magnetic field is given by
$  & upright("for ") 0 < x < L : &  & b (x , z) = B_0 + sum_(n = 1)^oo X_n (x) cos lambda_n z\
 & upright("for ") L < x : &  & b (x , z) = sum_(n = 1)^oo X_n (x) cos lambda_n z $<eq:magnetic_field_solution>

 *Force equations*\
<force-equations>
The attracting force of the magnet is given by
$ F_a = 1 / mu_0 integral_(- oo)^oo d x integral_a^a d z (b (x , z))^2 $
For a static magnetic this results in $ F_a^0 = 2 / mu_0 a L B_0^2 $
Substituting equation @eq:magnetic_field_solution the losses due to eddy
current are now incorporated in the force equation
$ F_a = F_a^0 sum_(n = 1)^oo c_n^2 f (n) $ with
$ f (n) = & #h(0.5em) frac(1, 2 L) \( L + frac(beta_n', alpha_n) (2 + beta_n ') (1 - exp - alpha_n L) \
  & + frac(alpha_n', beta_n) (2 - alpha_n ') \( 1 - exp beta_n L + 2 frac(alpha_n' beta_n', alpha_n + beta_n) (exp - alpha_n L - exp beta_n L) $
where $alpha_n = frac(alpha_n, alpha_n - beta_n)$ and
$beta_n = frac(beta_n, alpha_n - beta_n)$. \
The breaking force is given by
$ F_b & = frac(g, d mu_0) integral_(- oo)^oo d x integral_0^(2 d) d y integral_a^a d z (b_e frac(partial b_i, partial x) + 1 / 2 frac(partial b_i^2, partial x))\
 & = F_a^0 g / L sum_(n = 1)^oo (c_n^2 (alpha_n ' (exp beta_n L - 1) + beta_n ' (exp - alpha_n L - 1))) $

== Numerical model <numerical-model>
In the following section a self developed model, which takes the
induction law into account, is presented. First, we consider the
movement of the pod with the general law of movement
$ v_0 = frac(d x, d t) arrow.l.r.double d t = frac(d x, v_0) $ The
differential form of the magnetic flux is given as
$ d Phi = upright(bold(A)) dot.op d upright(bold(B)) + upright(bold(B)) dot.op d upright(bold(A)) $
but since the cross-section does not change, we can simplify the
equation to $ d Phi = upright(bold(A)) dot.op d upright(bold(B)) $

We consider a small cross-section here which is given as
$A = l med d x$, with $l$ as the width of the rail. So the induced
voltage in the rail is given by Faraday’s law of induction
$ V_(upright(i n d)) = - frac(d Phi, d t) = - frac(d Phi, d x) v_0 = - frac(partial B, partial x) med l med v_0 med d x $
Together with Ohm’s law, we can calculate the current density in the
rail
$ j = I / A = frac(V_(upright(i n d)), R med A) = frac(partial B, partial x) v_0 1 / rho d x $
A volume element can be described by $d V = h med l med d x$, so the
induced B-field can be expressed by the Biot-Savart law as follows
$ B_(upright(i)) (x) = frac(mu, 4 pi) frac(h med l, rho) v_0 integral_(- oo)^(+ oo) frac(partial B, partial x)\|_(x') 1 / (x - x ')^2 d^2 x' $
Here the magnetic field $B$ is the superposition of applied and induced
field, i.e. $B = B_0 + B_i$. Since the induced field depends on itself
an analytical solution is difficult and not yet found by the author. To
solve this equation we follow a numerical Ansatz: at a first step, $B$
is calculated only by the external field $B_0$. Then an iteration
follows, which calculates the magnetic field regarding the induced field
from the former step. \
At the end the converged $B_i$ and the applied Field are added to
retrieve the resulting field.
