#pagebreak()

#import "@preview/unify:0.7.1": num,qty,numrange,qtyrange
#import "@preview/physica:0.9.6": *

= Eddy Current Models<chapter:eddy_currents_models>

In the following chapter, different models are presented to describe the
eddy currents which are generated by the magnetic field and the movement
of the magnet.

== Yamamura model
<yamamura-model>
In his paper from 1975 @yamamura1975, Yamamura proposed an analytical model for speed characteristics of attracting magnets for magnetic levitation. The model here is simplified in the following form that rail and magnet core are not bent any more but are straight as shown in figure @fig:yamamura_simplified.
#figure(caption: [Comparison of the magnetic circuit and the simplified magnetic circuit],
  grid(columns: 2,
  column-gutter: 1em,
  row-gutter: 0.5em,
  [#image("../figures/models/mag_circuit.svg", width: 100%)],
  [#image("../figures/models/yamamura_simplified.svg", width: 70%)],
  [(a) Schematic of the magnetic circuit],[(b) Schematic of the simplified magnetic circuit]
  )
)<fig:yamamura_simplified>

We use the following three equations:
$ vb(J) = sigma (vb(E) + vb(v) times vb(B)) $<eq:current_density>
$ curl vb(E) = 0 $<eq:maxwell_E1>
$ curl vb(B) = mu vb(J) $
The first one is the generalized Ohm's law as introduced in @chapter:ohms_law, which describes the current density in the conductor generated by an electric field $vb(E)$ and the Lorentz force, which depends on the magnetic field $vb(B)$ and the velocity $vb(v)$.
The second one is the third Maxwell equation assuming no time derivation of the magnetic field, i.e. $pdv(vb(B),t)=0$.
The third one is the fourth Maxwell equation without the displacement current, which can be neglected as discussed in @displacement-current.
The inclusion of the Lorentz term $vb(v) times vb(B)$ in Ohm's law, together with the assumption of a time independent magnetic field corresponds to the observer frame of the magnet, i.e. a stationary magnet and a moving conductor.
\
With the fourth Maxwell equation (or Ampère's law, which can be derived from it), we consider a closed path as shown in @fig:closed_path.
#figure(caption: [Closed Path in x-y plane. Integrated along the red line],
  // placement: left,
  image("../figures/models/closed_path.svg", width:30%)
)<fig:closed_path>
Applying Ampère's law results in:
$ integral.cont vb(B) dot dd(vb(s)) &= mu_0 I \
  -B_y (x) (2d+2g) + B_y (x+dd(x)) (2d+2g) &= mu_0 j_z  2d dot dd(x)
$
Here we assume that the current is equally distributed over the whole thickness (in y direction) of the conductor and we write in the following $b$ instead of $B_y$. However, Yamamura reduced the height $2d+2g$ of the path to just $2g$.
In z direction we can also apply Ampère's law on a closed path, which then results in the two equations:
$ pdv(b, x) = frac(mu_0 d, g) j_z $<eq:path_integraded1>
$ pdv(b, z) = - frac(mu_0 d, g) j_x $<eq:path_integraded2>
Combining equation @eq:maxwell_E1 and @eq:current_density and applying a cross product on them holds following equation:
$ curl vb(J) = sigma curl (vb(v) times vb(B)) $<eq:curlJ>
Inserting equations @eq:path_integraded1 and @eq:path_integraded2 into
equation @eq:curlJ yields:
$ pdv(b, x, 2) + pdv(b, z, 2) - K pdv(b, x) = 0 $<eq:wave_equation>
where $K = frac(mu_0 sigma d v, g)$.
The magnetic flux density can be split into two parts, the component $b_e$ excited by the coils and the component $b_i$ induced by the eddy currents in the rail.
$ b = b_e + b_i $
So we can write an differential equation for the induced component $b_i$, which is excited by a function $f(x)$:
$ pdv(b_i, x, 2) + pdv(b_i, z, 2) - K pdv(b_i, x) &= f(x) \
 f(x) &= - pdv(b_e, x, 2) - pdv(b_e, z, 2) + K pdv(b_e, x) $<eq:wave_equation_induced>
Assumption is made that the excited component $b_e$ is
constant $B_0$ inside the air gap along the magnet and 0 elsewhere.
$ b_e = B_0 (u (x) - u (x - L)) (u (z + a) - u (z - a)) $<eq:solution_b_e>
$u (x)$ and $u (z)$ are step functions.
Within the air gap $(0 < x < L , - a < z < a)$ the derivation of $b_e$ is 0 there, so equation @eq:wave_equation_induced simplifies to
$ pdv(b_i, x, 2) + pdv(b_i, z, 2) - K pdv(b_i, x) = 0 $<eq:simplified_wave_equation>
An Ansatz of separated variables is assumed
$ b_i (x , z) = X (x) Z (z) $<eq:separated_variables>
which leads to
$
  X''/X - K X'/X + Z''/Z = 0
$
$ => X''/X - K X'/X = -Z''/Z = "const." := lambda_n $
$ => dv(Z (z), z, 2) + lambda_n Z (z) = 0 $
$
  => dv(X(x), x, 2) - K dv(X(x), x) - lambda_n X(x) = 0
$
where $lambda_n$ is an arbitrary constant. Boundary conditions are $b_i = 0$ at
$z = plus.minus a$ which gives following solution
$ Z (z) = cos (lambda_n z) $<eq:solution_z>
$ lambda_n = (2 n - 1) frac(pi, 2 a) $
Combining equations @eq:solution_z and @eq:separated_variables yields
$ b_i (x , z) = X (x) cos (lambda_n z) $ \
The step functions in equation @eq:solution_b_e can be expressed by
following Fourier series
$ u (z + a) - u (z - a) = sum_(n = 1)^oo c_n cos lambda_n z $
$ c_n = frac(4, pi (2 n - 1)) sin frac(2 n - 1, 2) pi $
\
Regarding the exciting component of equation @eq:wave_equation_induced, neglecting $frac(partial^2 b_e, partial z^2)$ (since motion is only in $x$-direction) and considering $pdv(u(x),x)=delta(x)$ holds
#math.equation([$
  f(x,z) &= -dv(b_e, x, 2) + K dv(b_e, x) \
   &= B_0 [- dv((delta (x) - delta (x - L)), x) &+ K (delta (x) - delta (x - L))] dot (sum_(n = 1)^oo c_n cos lambda_n z) \ .  $
], block:true, number-align: top)
We assume again an Ansatz of separated variables for equation @eq:wave_equation_induced which yields:
$ X''Z -K X' Z + Z'' X  = f $<separated_variables>
Inserting the solution of Z @eq:solution_z the following equation results:
$ & dv(X, x, 2) - K dv(X, x) - lambda_n^2  X \ & = C_n B_0 \( - dv((delta (x) - delta (x - L)), x) + K (delta (x) - delta (x - L))) $
This equation can effectively be solved by Fourier transformation:
$
-omega^2 tilde(X) - i omega K tilde(X) - lambda_n^2  tilde(X) = C_n B_0  (-(i omega - i omega e^(i omega L)) + K (1-e^(i omega L))
\
tilde(X) = C_n B_0 frac(i omega (1-  e^(i omega L)) - K (1-e^(i omega L)), omega^2 + i omega K + lambda_n^2)
$
\
The solution is
#math.equation([
$  & upright("for ") x < 0 : &  & X_n (x) = c_n B_0 frac(alpha_n, alpha_n - beta_n) (exp { - beta_n x } - exp { - beta_n (x - L) })\
 & upright("for ") 0 < x < L : &  & X_n (x) = c_n B_0 frac(1, alpha_n - beta_n) (beta_n exp { - alpha_n x } - alpha_n exp { - beta_n (x - L) })\
 & upright("for ") L < x : &  & X_n (x) = c_n B_0 frac(beta_n, alpha_n - beta_n) (exp { - alpha_n x } - exp { - alpha_n (x - L) }) $
], block:true, number-align: bottom)
with the following factors:
$ alpha_n & = 1 / 2 (- K + sqrt(K^2 + 4 lambda_n^2)) $
$ beta_n & = 1 / 2 (- K - sqrt(K^2 + 4 lambda_n^2)) $
So the solution for the magnetic field is given by
$  & upright("for ") 0 < x < L : &  & b (x , z) = B_0 + sum_(n = 1)^oo X_n (x) cos lambda_n z\
 & upright("for ") L < x : &  & b (x , z) = sum_(n = 1)^oo X_n (x) cos lambda_n z $<eq:magnetic_field_solution>
This model was written in python by the author to calculate some magnetic profiles for different velocity values. It was assumed a rail thickness of $qty("35", "mm")$ and an air gap of $qty("10", "mm")$. The results are shown in figure @fig:magnetic_profiles_yam_org.
#figure(caption:[Magnetic Profiles derived from the original Yamamura model],
  image("../figures/models/Yamamura_org.svg", width:100%)
)<fig:magnetic_profiles_yam_org>

 *Force equations*\
<force-equations>
The attracting force of the magnet is given by
$ F_a = 1 / mu_0 integral_(- oo)^oo d x integral_a^a d z (b (x , z))^2 $
For a static magnetic this results in $ F_a^0 = 2 / mu_0 a L B_0^2 $
Substituting equation @eq:magnetic_field_solution the losses due to eddy
current are now incorporated in the force equation
$ F_a = F_a^0 sum_(n = 1)^oo c_n^2 f (n) $ with
$ f (n) = & #h(0.5em) frac(1, 2 L) \( L + frac(beta_n', alpha_n) (2 + beta_n ') (1 - exp - alpha_n L) \
  & + frac(alpha_n', beta_n) (2 - alpha_n ') \( 1 - exp beta_n L + 2 frac(alpha_n' beta_n', alpha_n + beta_n) (exp - alpha_n L - exp beta_n L) $
where $alpha_n = frac(alpha_n, alpha_n - beta_n)$ and
$beta_n = frac(beta_n, alpha_n - beta_n)$. \
The breaking force is given by
$ F_b & = frac(g, d mu_0) integral_(- oo)^oo d x integral_0^(2 d) d y integral_a^a d z (b_e frac(partial b_i, partial x) + 1 / 2 frac(partial b_i^2, partial x))\
 & = F_a^0 g / L sum_(n = 1)^oo (c_n^2 (alpha_n ' (exp beta_n L - 1) + beta_n ' (exp - alpha_n L - 1))) $


== Adaption of Yamamura Model
In the original Yamamura model, the undisturbed magnetic field $b_e$ generated by the coils at zero speed is represented by a rectangular function. In this work, the model is extended to accept an arbitrary input function for $b_e$. Specifically, we use a magnetic field profile obtained from a simulation of a stationary magnet located beneath a rail.
In fact, we actually only want to have an arbitrary input for the magnetic field along the x direction profile. The z-component should have the same constraints as in the Yamamura model. So we consider again a function with separated variables:
$ b_e (x,z) = b_(e, x)(x) b_(e, z)(z) $
As z-component we use the one derived from the original model. That gives us following exciting component $f$:
$ f(x,z) = -pdv(b_e, x ,2) + K pdv(b_e, x) = (-dv(b_(e, x), x, 2) + K dv(b_(e, x), x)) Z(z) $
Inserting in equation @separated_variables yields:
$ dv(X, x, 2) - K dv(X, x) - lambda_n^2  X = C_n (-dv(b_(e, x), x, 2) + K dv(b_(e, x), x)) $
Transforming this equation into the frequency domain yields:
$ -omega^2 tilde(X) + i omega K tilde(X) + lambda_n^2  tilde(X) = C_n (omega^2 tilde(b)_(e, x) + i omega K tilde(b)_(e, x)) $
$ tilde(X) = C_n (omega^2 + i omega K ) / (-omega^2 + i omega K + lambda_n^2) tilde(b)_(e, x) $
So the solution is:
$ b(x, z) &= b_e + b_i \ &= sum_(n = 1)^oo b_(e, x)(x) c_n cos(lambda_n z) + X_n (x) cos(lambda_n z) $
with
$ X_n(x) = C_n cal(F)^(-1)((omega^2 + i omega K ) / (-omega^2 + i omega K + lambda_n^2) cal(F)(b_(e, x)(x))) $
\
This adapted model is also written in python by the author. Since the Fourier transform cannot be calculated analytically anymore, a numerical approach is used to calculate the Fourier transform. The numerical approach is based on the Fast Fourier Transform (FFT) algorithm, which is a fast and efficient method for calculating the Fourier transform of a signal. The FFT algorithm is implemented in the _scipy_ library in python.
For computation the same values for rail thickness and air gap are used as in the Yamamura model, the result is shown in @fig:magnetic_profiles_yam_02.
#figure(caption:[Magnetic Profiles derived from the adapted Yamamura model],
  image("../figures/models/Yamamura_02.svg", width:100%)
)<fig:magnetic_profiles_yam_02>
\

#pagebreak()
== Sinha Model
P. K. Sinha described in his book @sinha1987electromagnetic a similar model to describe the eddy currents induced by a moving magnetic field along a conducting rail. \
In this approach, @eq:current_density is also used but then the macroscopic Maxwell @maxwell_H2 and instead of the static one in Yamamura's approach the dynamic @maxwell_E2. Combining these results in the following differential equation:
$ frac(1, mu sigma)laplacian H = pdv(H, t) + curl (v times H) $
which becomes for an electromagnetic suspension system with a geometry as shown in @fig:yamamura_simplified :
$ frac(1, mu_0 sigma) laplacian B(x,y,z,t) approx frac(2a, 2z) (pdv(B(x,y,z,t), t)) $.
Following assumptions are made for analytical convenience:
- uniform flux density across the width of the airgap: $pdv(B, z) = pdv(B^2, z, 2) =0$
- the magnet moves only in the x direction with constant velocity $v$:\ $v=dv(x, t)$, $dv(y, t)=dv(z, t)=0$
- the flux density $B$ is split into two components, the induced flux $B_i$ due to the eddy currents and the excited flux $B_e$ of the magnet current, which is constant $B_0$ over the length of the magnet and $0$ elsewhere.
These relationships combined results in the following differential equation for the airgap:
$
pdv(B_i, x, 2) + pdv(B_i, y, 2) - k pdv(B_i, x) \
= - B_0 (pdv(Delta(x), x)-pdv(Delta(x-l), x))dot(f(y+overline(p))-f(y-overline(p))) + k B_0 (Delta(x)-Delta(x-l)) dot (f(y+overline(p))-f(y-overline(p)))
$
where $k=mu_0 sigma overline(p)v/z$, $Delta(x)$ the appropriate impulse function and $f(x)$ a step function.

#pagebreak()
== Numerical Model <numerical-model>
In the following section a self developed model, which takes the
induction law into account, is presented. First, we consider the
movement of the pod with the general law of movement
$ v_0 = dv(x, t) arrow.l.r.double dd(t) = frac(dd(x), v_0) $ The
differential form of the magnetic flux is given as
$ dd(Phi) = vb(A) dot.op dd(vb(B)) + vb(B) dot.op dd(vb(A)) $
but since the cross-section does not change, we can simplify the
equation to $ dd(Phi) = vb(A) dot.op dd(vb(B)) $

We consider a small cross-section here which is given as
$A = l med dd(x)$, with $l$ as the width of the rail. So the induced
voltage in the rail is given by Faraday's law of induction
$ V_(upright(i n d)) = - dv(Phi, t) = - dv(Phi, x) v_0 = - pdv(B, x) med l med v_0 med dd(x) $
Together with Ohm's law, we can calculate the current density in the
rail
$ j = I / A = frac(V_(upright(i n d)), R med A) = pdv(B, x) v_0 1 / rho dd(x) $
A volume element can be described by $dd(V) = h med l med dd(x)$, so the
induced B-field can be expressed by the Biot-Savart law as follows
$ B_(upright(i)) (x) = frac(mu, 4 pi) frac(h med l, rho) v_0 integral_(- oo)^(+ oo) pdv(B, x)\|_(x') 1 / (x - x ')^2 dd(x, 2)' $
Here the magnetic field $B$ is the superposition of applied and induced
field, i.e. $B = B_0 + B_i$. Since the induced field depends on itself
an analytical solution is difficult and not yet found by the author. To
solve this equation we follow a numerical Ansatz: at a first step, $B$
is calculated only by the external field $B_0$. Then an iteration
follows, which calculates the magnetic field regarding the induced field
from the former step. \
At the end the converged $B_i$ and the applied Field are added to
retrieve the resulting field.
